
---
galaxy_info:
  role_name: "setup_local"
  standalone: false
  company: ""
  description: >
    Setup local environment with required tools
  author: rprakashg
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.12"
  platforms:
  galaxy_tags:
    - tools
    - setup
    - environment
dependencies: []
