- name: install openshift tools
  become: true
  block:
    - name: Check if bin path dir exists
      ansible.builtin.stat:
        path: "{{ binDir }}"
      register: bin_stat

    - name: Create bin path dir if doesnt exist
      ansible.builtin.file:
        path: "{{ binDir }}"
        state: directory
        mode: '0755'
      when: not bin_stat.stat.exists
    
    - name: set download file based on target platform
      set_fact:
        openshift_installer: >
          {% elif ansible_facts['os_family'] == 'RedHat' %}
            openshift-install-linux.tar.gz
          {% else %}
            openshift-install-mac.tar.gz
          {% endif %}
        openshift_client: >
          {% elif ansible_facts['os_family'] == 'RedHat' %}
            openshift-client-linux.tar.gz
          {% else %}
            openshift-client-mac.tar.gz
          {% endif %}
    
    - name: create a temp downloads directory
      tempfile:
        state: directory
        suffix: downloads
      register: downloads_tmp

    - name: download openshift installer
      ansible.builtin.get_url:
        url: "{{ mirrorUrl }}/{{ openshift_installer }}"
        dest: "{{ downloads_tmp.path }}/{{ openshift_installer }}"
        mode: '0755'

    - name: Untar downloaded artifact
      unarchive:
        src: "{{ downloads_tmp.path }}/{{ openshift_installer }}"
        dest: "{{ downloads_tmp.path }}"
        remote_src: yes
        extra_opts: ['--strip-components=1', '--show-stored-names']
    
    - name: move the openshift installer binary to bin dir
      file:
        src: "{{ downloads_tmp.path }}/openshift-install"
        dest: "{{ binDir }}"
        state: move

    - name: download openshift client
      ansible.builtin.get_url:
        url: "{{ mirrorUrl }}/{{ openshift_client }}"
        dest: "{{ downloads_tmp.path }}/{{ openshift_client }}"
        mode: '0755'

    - name: Untar downloaded artifact
      unarchive:
        src: "{{ downloads_tmp.path }}/{{ openshift_client }}"
        dest: "{{ downloads_tmp.path }}"
        remote_src: yes
        extra_opts: ['--strip-components=1', '--show-stored-names']
    
    - name: move oc and kubectl binaries to bin dir
      file:
        src: "{{ downloads_tmp.path }}/oc"
        dest: "{{ binDir }}"
        state: move

    - name: move oc and kubectl binaries to bin dir
      file:
        src: "{{ downloads_tmp.path }}/kubectl"
        dest: "{{ binDir }}"
        state: move    