- name: install homebrew
  become: true
  block:
    - name: verify xcode installed
      ansible.builtin.shell:
        cmd: xcode-select -p
      register: xcode_select_output
      ignore_errors: yes
    
    - name: check return code
      ansible.builtin.debug:
        msg: >
          {% if xcode_select_output.rc == 0 %}
            Xcode command line tools are installed.
          {% else %}
            Xcode command line tools are not installed.
          {% endif %}

    - name: Install if return code not equal to 0
      become: true
      command: softwareupdate --install -a
      when: xcode_select_output.rc != 0

    - name: Accept Xcode license agreement
      become: true
      command: xcodebuild -license accept
      when: xcode_select_output.rc != 0

    - name: Ensure Homebrew is installed
      community.general.homebrew:
        state: present

    - name: Verify Homebrew installation
      ansible.builtin.shell:
        cmd: /usr/local/bin/brew --version
      register: brew_version

    - name: Print Homebrew version
      debug:
        msg: "Homebrew version: {{ brew_version.stdout }}"
  when: installPackageManager | default(true)

- name: install git
  block:
    - name: Install git
      community.general.homebrew:
        name: git
        state: present
    
    - name: Verify git
      ansible.builtin.shell:
        cmd: git --version
      register: git_version
    
    - name: Print git version
      debug:
        msg: "Git version: {{ git_version }}"
  when: installGit | default(true)